#pragma once

#include "../Base/DirectXCommon.h"
#include "../Base/WinApp.h"
#include "../Input/Input.h"
#include "../ImGui/ImGuiManager.h"
#include "../Resource/Texture/TextureManager.h"
#include "../Sprite/Sprite.h"
#include "../Model/Model.h"
#include "../Particle/ParticleManager.h"
#include "../Particle/Particle.h"
#include "..//Collider/CollisionManager.h"
#include "../Object/ViewProjection.h"
#include "../Configs/GlobalConfigs.h"
#include "../Object/3D/3dObjectList.h"